spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: postgres
    password: password

  jooq:
    sql-dialect: postgres

  flyway:
    enabled: true
    locations: classpath:db/migration