CREATE TABLE users (
    id BIGSERIAL PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL ,
    ROLE VARCHAR(50) NOT NULL ,
    CREATED_AT TIMESTAMP DEFAULT NOW()
);